### ISSUE TITLE
Support for redmine 3.x?

### ISSUE THREAD

**Issue by ilovetacos** [alpcrimea/redmine-spectator-plugin#1]
Hi,
i was wondering if you are going to release an upgrade supporting redmine v3.x?
I use this plugin and want to upgrade my redmine installation.
Thank you very much!

**Comment by alpcrimea** [comment]
Hi. I'm going to migrate to Redmine 3.1.0 soon. So it's in my foreground.

Thank you for using my plugin!

**Comment by ilovetacos** [comment]
Thank you very much for your reply and for the great plugin :)

**Comment by alpcrimea** [comment]
As I can see plugin is working with redmine 3.0.4.You can try to upgrade.

**Comment by ilovetacos** [comment]
Thanks. I'm using many other plugins and I don't know if they work with v3.x. I'd rather wait a bit and see if they get upgraded.
